version: '3'

services:
 web:
    container_name: airsketch_django_web
    build: .
    command: python manage.py runserver 0.0.0.0:3000
    volumes:
      - .:/airsketch_django_app
      - airsketch_db:/airsketch_django_app/database
    ports:
      - "3000:3000"

volumes:
 airsketch_db:
